site_name: FLORES+ Mayas
nav: 
  - Inicio: index.md
  - Qué es FLORES+: flores.md
  - Tarea de traducción: 
    - Directrices para el control de calidad:
      - Tipología de errores: directrices/tipologia.md
      - Aspectos por considerar: directrices/aspectos.md
    - Cronograma de actividades: tarea/cronograma.md 
    - Guía de traducción: tarea/guia.md 
    - Cómo rellenar la guía de traducción: tarea/como_rellenar.md 
    - Prácticas predeterminadas: tarea/predeterminada.md 


      # - Tarea de traducción:
      #    - Cronograma de actividades: tarea/cronograma.md 
  #- Vocabularios y textos paralelos: textos.md
  # - JW Crawler: jw.md
  #- FLORES-Mayas: flores.md
  # - Sobre el proyecto: about.md
  # - Cómo colaborar: colaborar.md
theme:
  name: windmill
  language: es
extra_css:
  - style.css
markdown_extensions:
  - footnotes
