site_name: FLORES+ Mayas
nav: 
  - Inicio: index.md
  - Qué es FLORES+: flores.md
  - Tarea de traducción: 
    - Cronograma de actividades: tarea/cronograma.md 
    - Prácticas predeterminadas: tarea/predeterminada.md 
    - Protocolo de traducción:
      - tarea/protocolo/fases.md
      - tarea/protocolo/equipos.md
      - tarea/protocolo/interaccion.md 
      - tarea/protocolo/compensacion.md
    - Directrices para el control de calidad:
      - Tipología de errores: directrices/tipologia.md
      - Aspectos por considerar: directrices/aspectos.md
    - Guía de traducción: 
      - Qué es la guía de traducción: tarea/guia.md 
      - Cómo rellenar la guía de traducción: tarea/como_rellenar.md 
theme:
  name: windmill
  language: es
extra_css:
  - style.css
markdown_extensions:
  - footnotes
