name: update_packets

on:
  schedule:
    - cron: '*/5 * * * *' 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: install reqs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: install apertium
        run: |
          sudo apt update
          sudo apt update --fix-missing
          sudo apt install apertium
          sudo apt install apertium-eng-spa

      - name: decrypt floresp
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE_FLORESP }}" --output flores_plus_translation_task/data/flores.eng-spa.dev flores_plus_translation_task/data/flores.eng-spa.dev.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE_FLORESP }}" --output flores_plus_translation_task/data/flores.eng-spa.devtest flores_plus_translation_task/data/flores.eng-spa.devtest.gpg
          echo $(ls flores_plus_translation_task/data/flores.eng-spa.devtest)
          echo $(ls flores_plus_translation_task/data/flores.eng-spa.dev)

      - name: update packets 
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          EMAIL_ADRESS: ${{ secrets.EMAIL_ADRESS }}
          EMAIL_PASSWD: ${{ secrets.EMAIL_PASSWD }}
        run: |
          cd flores_plus_translation_task/src
          echo $AUTH_TOKEN > token.json
          python update_packets.py 

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git rm --cache flores_plus_translation_task/data/flores.eng-spa.dev
          git rm --cache flores_plus_translation_task/data/flores.eng-spa.devtest
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
            
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
